<a href="https://colab.research.google.com/github/thanvanth46/flipcart-sales-dataset/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Welcome to Colab!

In [4]:
import pandas as pd
import numpy as np
df=pd.read_csv("/content/flipkart_sales (1).csv")
df

,Order ID,Product Name,Category,Price (INR),Quantity Sold,Total Sales (INR),Order Date,Payment Method,Customer Rating
0,ORD00001,Educational Book,Books,49069.56,2,98139.12,2024-09-12,Debit Card,3.5
1,ORD00002,Jeans,Clothing,12755.85,4,51023.40,2024-12-18,UPI,3.9
2,ORD00003,Face Cream,Beauty,11092.19,4,44368.76,2024-05-18,Debit Card,4.4
3,ORD00004,Smartwatch,Electronics,32657.81,1,32657.81,2024-11-08,Debit Card,3.2
4,ORD00005,Cookware Set,Home & Kitchen,26590.08,3,79770.24,2024-12-27,UPI,3.1
...,...,...,...,...,...,...,...,...,...
995,ORD00996,Smartphone,Electronics,28995.81,3,86987.43,2025-01-13,COD,5.0
996,ORD00997,Perfume,Beauty,32799.51,2,65599.02,2024-12-18,Wallet,2.4
997,ORD00998,Face Cream,Beauty,40840.80,1,40840.80,2024-07-26,UPI,3.1
998,ORD00999,Cookware Set,Home & Kitchen,34741.79,4,138967.16,2024-10-02,Net Banking,3.2
999,ORD01000,Table Lamp,Home & Kitchen,16698.12,4,66792.48,2024-03-26,Credit Card,1.6

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Order ID           1000 non-null   object
 1   Product Name       1000 non-null   object
 2   Category           1000 non-null   object
 3   Price (INR)        1000 non-null   float64
 4   Quantity Sold      1000 non-null   int64
 5   Total Sales (INR)  1000 non-null   float64
 6   Order Date         1000 non-null   object
 7   Payment Method     1000 non-null   object
 8   Customer Rating    1000 non-null   float64
dtypes: float64(3), int64(1), object(5)
memory usage: 70.4+ KB

In [6]:
print(df.shape)

(1000, 9)

In [7]:
print(df.columns)

Index(['Order ID', 'Product Name', 'Category', 'Price (INR)', 'Quantity Sold',
       'Total Sales (INR)', 'Order Date', 'Payment Method', 'Customer Rating'],
      dtype='object')

In [8]:
print(df.isnull().sum())

Order ID             0
Product Name         0
Category             0
Price (INR)          0
Quantity Sold        0
Total Sales (INR)    0
Order Date           0
Payment Method       0
Customer Rating      0
dtype: int64

In [9]:
df=df.dropna()

In [10]:
df.loc[3-1,'Category']

'Beauty'

In [11]:
df.loc[3:7,'Product Name']

3       Smartwatch
4     Cookware Set
5    Mixer Grinder
6         Sneakers
7       Table Lamp
Name: Product Name, dtype: object

In [12]:
df.loc[[1,3,4,5,8,2],['Product Name','Category','Price (INR)','Quantity Sold','Total Sales (INR)','Order Date']]

,Product Name,Category,Price (INR),Quantity Sold,Total Sales (INR),Order Date
1,Jeans,Clothing,12755.85,4,51023.40,2024-12-18
3,Smartwatch,Electronics,32657.81,1,32657.81,2024-11-08
4,Cookware Set,Home & Kitchen,26590.08,3,79770.24,2024-12-27
5,Mixer Grinder,Home & Kitchen,10475.03,2,20950.06,2024-10-22
8,Jacket,Clothing,1987.39,2,3974.78,2025-01-18
2,Face Cream,Beauty,11092.19,4,44368.76,2024-05-18

In [20]:
cate=df[df['Category']=='Clothing']
cate['Category'].unique()

array(['Clothing'], dtype=object)

In [21]:
cate['Category'].unique()

array(['Clothing'], dtype=object)

In [22]:
cate

,Order ID,Product Name,Category,Price (INR),Quantity Sold,Total Sales (INR),Order Date,Payment Method,Customer Rating
1,ORD00002,Jeans,Clothing,12755.85,4,51023.40,2024-12-18,UPI,3.9
6,ORD00007,Sneakers,Clothing,38647.72,3,115943.16,2024-07-04,Wallet,2.0
8,ORD00009,Jacket,Clothing,1987.39,2,3974.78,2025-01-18,Debit Card,2.6
19,ORD00020,T-Shirt,Clothing,32565.77,5,162828.85,2025-01-06,COD,4.4
21,ORD00022,Jeans,Clothing,37129.73,3,111389.19,2025-01-22,Wallet,4.3
...,...,...,...,...,...,...,...,...,...
973,ORD00974,T-Shirt,Clothing,1434.23,2,2868.46,2024-03-24,UPI,3.5
983,ORD00984,Jeans,Clothing,22890.95,3,68672.85,2024-11-30,Credit Card,3.0
984,ORD00985,Jeans,Clothing,40905.69,5,204528.45,2025-01-27,COD,1.9
987,ORD00988,Jacket,Clothing,46055.88,5,230279.40,2024-12-06,COD,4.2
994,ORD00995,Sneakers,Clothing,11479.89,3,34439.67,2024-07-30,Net Banking,2.5

In [26]:
df[(df['Category']=='Clothing') & (df['Quantity Sold']==4)]

,Order ID,Product Name,Category,Price (INR),Quantity Sold,Total Sales (INR),Order Date,Payment Method,Customer Rating
1,ORD00002,Jeans,Clothing,12755.85,4,51023.40,2024-12-18,UPI,3.9
25,ORD00026,T-Shirt,Clothing,2053.11,4,8212.44,2024-07-23,COD,3.4
26,ORD00027,Jeans,Clothing,38927.62,4,155710.48,2024-08-24,Wallet,2.5
74,ORD00075,Sneakers,Clothing,1542.10,4,6168.40,2024-08-25,Credit Card,1.0
110,ORD00111,Jacket,Clothing,35811.10,4,143244.40,2024-09-11,Net Banking,1.9
114,ORD00115,Jacket,Clothing,26219.99,4,104879.96,2024-03-14,Debit Card,2.1
135,ORD00136,Jacket,Clothing,14043.16,4,56172.64,2024-06-01,Wallet,3.1
202,ORD00203,Sneakers,Clothing,16468.59,4,65874.36,2024-10-24,Net Banking,4.5
217,ORD00218,Dress,Clothing,44241.68,4,176966.72,2024-09-18,COD,1.4
250,ORD00251,Jacket,Clothing,1987.98,4,7951.92,2024-02-23,UPI,3.3
255,ORD00256,Jacket,Clothing,15068.72,4,60274.88,2024-03-23,Debit Card,1.4
279,ORD00280,Sneakers,Clothing,22968.18,4,91872.72,2025-01-23,Net Banking,4.1
307,ORD00308,Dress,Clothing,25379.68,4,101518.72,2024-10-06,Wallet,3.5
315,ORD00316,T-Shirt,Clothing,41198.84,4,164795.36,2024-04-08,Credit Card,3.0
333,ORD00334,Jacket,Clothing,26096.96,4,104387.84,2024-03-28,Debit Card,3.5
345,ORD00346,Sneakers,Clothing,46090.65,4,184362.60,2025-01-25,UPI,3.3
352,ORD00353,T-Shirt,Clothing,26166.89,4,104667.56,2024-09-06,Credit Card,3.7
359,ORD00360,Dress,Clothing,7936.32,4,31745.28,2024-09-21,Credit Card,1.5
378,ORD00379,Sneakers,Clothing,29310.76,4,117243.04,2024-07-03,Wallet,4.4
380,ORD00381,Jacket,Clothing,24062.33,4,96249.32,2025-01-19,Debit Card,1.1
394,ORD00395,Sneakers,Clothing,34369.57,4,137478.28,2024-07-31,Net Banking,1.6
413,ORD00414,Dress,Clothing,42975.36,4,171901.44,2024-08-18,COD,3.3
450,ORD00451,Sneakers,Clothing,3995.44,4,15981.76,2024-05-26,Debit Card,4.0
469,ORD00470,T-Shirt,Clothing,36666.62,4,146666.48,2024-09-28,Net Banking,2.1
480,ORD00481,Jacket,Clothing,18757.07,4,75028.28,2024-11-16,UPI,4.2
485,ORD00486,Dress,Clothing,45426.39,4,181705.56,2024-10-31,Net Banking,2.8
492,ORD00493,T-Shirt,Clothing,45127.31,4,180509.24,2025-01-15,COD,4.2
535,ORD00536,Dress,Clothing,42794.40,4,171177.60,2024-06-25,COD,4.6
561,ORD00562,Jeans,Clothing,37503.57,4,150014.28,2024-04-03,COD,1.8
580,ORD00581,Jacket,Clothing,16129.77,4,64519.08,2024-06-19,Debit Card,1.0
585,ORD00586,Jeans,Clothing,26527.78,4,106111.12,2024-02-15,Net Banking,3.7
610,ORD00611,Jeans,Clothing,21417.72,4,85670.88,2024-07-20,Debit Card,4.5
623,ORD00624,T-Shirt,Clothing,18161.01,4,72644.04,2024-07-13,Credit Card,2.3
662,ORD00663,Jeans,Clothing,15282.31,4,61129.24,2024-06-17,Net Banking,2.1
670,ORD00671,T-Shirt,Clothing,19275.66,4,77102.64,2024-04-17,Net Banking,1.8
725,ORD00726,Sneakers,Clothing,48620.13,4,194480.52,2024-07-21,Debit Card,1.9
746,ORD00747,Sneakers,Clothing,36918.20,4,147672.80,2024-02-28,Wallet,3.2
796,ORD00797,Jeans,Clothing,27532.48,4,110129.92,2024-04-09,UPI,2.2
814,ORD00815,T-Shirt,Clothing,6114.55,4,24458.20,2024-08-27,Debit Card,3.7
854,ORD00855,Sneakers,Clothing,9655.03,4,38620.12,2024-11-16,Credit Card,1.5
884,ORD00885,Sneakers,Clothing,26550.66,4,106202.64,2024-03-09,COD,3.3
927,ORD00928,Jeans,Clothing,29604.77,4,118419.08,2024-05-06,Wallet,3.7
948,ORD00949,Jeans,Clothing,15543.65,4,62174.60,2024-05-31,Credit Card,2.7
961,ORD00962,Dress,Clothing,27369.17,4,109476.68,2024-09-11,UPI,3.5
969,ORD00970,T-Shirt,Clothing,879.25,4,3517.00,2024-09-07,Wallet,4.9